name: GPFlags
main: me.ryanhamshire.GPFlags.GPFlags
depend: [GriefPrevention]
softdepend: [mcMMO, Vault, MythicMobs, EliteMobs, DiscordSRV]
authors: [Big_Scary, ShaneBee, DmitryRendov, DrBot, soliddanii]
description: GriefPrevention add-on to set flags in claims.
website: https://www.spigotmc.org/resources/griefprevention-flags.55773/
version: '${project.version}'
api-version: '1.13'
commands:
  gpflags:
    description: Reload or get help
    usage: /GPFlags <reload|help>
    permission: gpflags.command.gpflags
  allflags:
    description: Sends a list of all flags and their flag type
    usage: /AllFlags
    aliases: [ listallflags, allflagslist ]
    permission: gpflags.command.allflags
  setclaimflag:
    description: Sets a flag on a GriefPrevention land claim.
    usage: /SetClaimFlag <flag> <optional parameters>
    aliases: [ setflag, placeflag, putflag, claimflag, placeclaimflag, putclaimflag ]
    permission: gpflags.command.setclaimflag
  setclaimflagplayer:
    description: Sets a flag on a GriefPrevention land claim for a player from console.
    usage: /SetClaimFlagPlayer <player> <flag> <optional parameters>
    aliases: [ setflagplayer, placeflagplayer, putflagplayer, claimflagplayer, placeclaimflagplayer, putclaimflagplayer ]
    permission: gpflags.command.setclaimflagplayer
  unsetclaimflag:
    description: Un-sets (removes) a flag on a GriefPrevention land claim.
    usage: /UnSetClaimFlag <flag>
    aliases: [ unsetflag, removeflag, unclaimflag, removeclaimflag ]
    permission: gpflags.command.unsetclaimflag
  unsetclaimflagplayer:
    description: Un-sets (removes) a flag on a GriefPrevention land claim for a player from console.
    usage: /UnSetClaimFlagPlayer <player> <flag>
    aliases: [ unsetflagplayer, removeflagplayer, unclaimflagplayer, removeclaimflagplayer ]
    permission: gpflags.command.unsetclaimflagplayer
  setdefaultclaimflag:
    description: Sets a flag on all GriefPrevention land claims.
    usage: /SetDefaultClaimFlag <flag> <optional parameters>
    aliases: [ setdefaultflag, placedefaultflag, putdefaultflag, defaultclaimflag, placedefaultclaimflag, putdefaultclaimflag ]
    permission: gpflags.command.setdefaultclaimflag
  unsetdefaultclaimflag:
    description: Un-sets (removes) a default flag from all GriefPrevention land claims.
    usage: /UnSetClaimFlag <flag>
    aliases: [ unsetdefaultflag, removedefaultflag, removedefaultclaimflag ]
    permission: gpflags.command.unsetdefaultclaimflag
  listclaimflags:
    description: Lists all the flags currently set on a GriefPrevention land claim.
    usage: /ListClaimFlags
    aliases: [ listclaimflags, claimflags, listflags ]
    permission: gpflags.command.listclaimflags
  setworldflag:
    description: Sets a flag on an entire world.
    usage: /SetWorldFlag <world> <flag> <optional parameters>
    aliases: [ placeworldflag, putworldflag, worldflag ]
    permission: gpflags.command.setworldflag
  unsetworldflag:
    description: Un-sets (removes) a world-level flag.
    usage: /UnSetWorldFlag <flag>
    aliases: [ unsetworldflag, removeworldflag, unworldflag ]
    permission: gpflags.command.unsetworldflag
  setserverflag:
    description: Sets a flag everywhere.
    usage: /SetServerFlag <flag> <optional parameters>
    aliases: [ placeserverflag, putserverflag, serverflag ]
    permission: gpflags.command.setserverflag
  unsetserverflag:
    description: Un-sets (removes) a server-level flag.
    usage: /UnSetServerFlag <flag>
    aliases: [ unsetserverflag, removeserverflag, unserverflag ]
    permission: gpflags.command.unsetserverflag
  buybuildtrust:
    description: Buy buildtrust in a claim.
    usage: /buybuildtrust
  buycontainertrust:
    description: Buy containertrust in a claim.
    usage: /buycontainertrust
  buyaccesstrust:
    description: Buy inventorytrust in a claim.
    usage: /buyinventorytrust
  buysubclaim:
    description: Buy the subclaim
    usage: /buysubclaim
permissions:
  gpflags.admin.*:
    description: Grants all administrative functionality. (depreciated)
    children:
      gpflags.admin: true
  gpflags.admin:
      description: Grants all administrative functionality.
      children:
          gpflags.command.setclaimflag: true
          gpflags.command.setdefaultflag: true
          gpflags.command.unsetdefaultflag: true
          gpflags.command.unsetclaimflag: true
          gpflags.command.setworldflag: true
          gpflags.command.unsetworldflag: true
          gpflags.command.setserverflag: true
          gpflags.command.unsetserverflag: true
          gpflags.command.listflags: true
          gpflags.command.reload: true
          gpflags.command.allflags: true
          gpflags.bypass.*: true
  gpflags.setflag:
      description: Grants permission to use /SetClaimFlag. (depreciated)
      default: op
      children:
        gpflags.command.setclaimflag: true
  gpflags.unsetflag:
      description: Grants permission to use /UnSetClaimFlag. (depreciated)
      default: op
      children:
        gpflags.command.unsetclaimflag: true
  gpflags.setworldflag:
      description: Grants permission to use /SetWorldFlag. (depreciated)
      default: op
      children:
        gpflags.command.setworldflag: true
  gpflags.unsetworldflag:
      description: Grants permission to use /UnSetWorldFlag. (depreciated)
      default: op
      children:
        gpflags.command.unsetworldflag: true
  gpflags.setserverflag:
      description: Grants permission to use /SetServerFlag. (depreciated)
      default: op
      children:
        gpflags.command.setserverflag: true
  gpflags.unsetserverflag:
      description: Grants permission to use /UnSetServerFlag. (depreciated)
      default: op
      children:
        gpflags.command.unsetserverflag: true
  gpflags.defaultflags:
      description: Grants permission to use /SetDefaultClaimFlag and /UnSetDefaultClaimFlag. (depreciated)
      default: op
      children:
        gpflags.command.setdefaultclaimflag: true
        gpflags.command.unsetdefaultclaimflag: true
  gpflags.listflags:
      description: Grants permission to use /ListClaimFlags. (depreciated)
      default: op
      children:
        gpflags.command.listflags: true
  gpflags.reload:
      description: Grants permission to use /GPFReload. (depreciated)
      default: op
      children:
        gpflags.command.reload: true
  gpflags.allflags:
      description: Grants permission to apply/remove all flags. (depreciated)
      default: op
      children:
        gpflags.command.allflags: true
  gpflags.bypass:
      description: Makes a player immune to the limitations of all flags (depreciated).
      default: false
      children:
          gpflags.bypass.*: true
  gpflags.bypass.commandblacklist:
    description: Makes a player immune to commandblacklist flags
    default: op
  gpflags.bypass.commandwhitelist:
    description: Makes a player immune to commandwhitelist flags
    default: op
  gpflags.bypass.noenter:
    description: Makes a player immune to noenter and noenterplayer flags
    default: op
  gpflags.bypass.novehicle:
    description: Makes a player immune to novehicle flags
    default: op
  gpflags.bypass.novehicle.ownclaim:
    description: Makes a player immune to their own novehicle flags
    default: op
  gpflags.bypass.novehicle.nonclaim:
    description: Makes a player immune to novehicle outside of claims
    default: op
  gpflags.bypass.novehicle.adminclaim:
    description: Makes a player immune to novehicle in adminclaims
    default: op
  gpflags.bypass.novehicle.manage:
    description: Makes a player immune to novehicle where they have manage trust
    default: op
  gpflags.bypass.novehicle.build:
    description: Makes a player immune to novehicle where they have build trust
    default: op
  gpflags.bypass.novehicle.inventory:
    description: Makes a player immune to novehicle where they have inventory trust
    default: true
  gpflags.bypass.novehicle.access:
    description: Makes a player immune to novehicle where they have access trust
    default: op
  gpflags.bypass.fly:
      description: Makes a player immune to ownerfly and ownermemberfly flags
      default: op
  gpflags.bypass.noflight:
      description: Makes a player immune to noflight flags
      default: op
  gpflags.bypass.exitcommand:
      description: Makes a player immune to exitcommand flags
      default: false
  gpflags.bypass.nochorusfruit:
    description: Makes a player immune to nochorusfruit flags
    default: op
  gpflags.bypass.nochorusfruit.nonclaim:
    description: Makes a player immune to nochorusfruit outside of claims
    default: op
  gpflags.bypass.nochorusfruit.adminclaim:
    description: Makes a player immune to nochorusfruit in adminclaims
    default: op
  gpflags.bypass.nochorusfruit.manage:
    description: Makes a player immune to nochorusfruit where they have manage trust
    default: op
  gpflags.bypass.nochorusfruit.build:
    description: Makes a player immune to nochorusfruit where they have build trust
    default: op
  gpflags.bypass.nochorusfruit.inventory:
    description: Makes a player immune to nochorusfruit where they have inventory trust
    default: op
  gpflags.bypass.nochorusfruit.access:
    description: Makes a player immune to nochorusfruit where they have access trust
    default: op
  gpflags.bypass.commandblacklist.ownclaim:
    description: Makes a player immune to their own commandblacklist flags
    default: op
  gpflags.bypass.commandblacklist.nonclaim:
    description: Makes a player immune to commandblacklist outside of claims
    default: op
  gpflags.bypass.commandblacklist.adminclaim:
    description: Makes a player immune to commandblacklist in adminclaims
    default: op
  gpflags.bypass.commandblacklist.manage:
    description: Makes a player immune to commandblacklist where they have manage trust
    default: op
  gpflags.bypass.commandblacklist.build:
    description: Makes a player immune to commandblacklist where they have build trust
    default: op
  gpflags.bypass.commandblacklist.inventory:
    description: Makes a player immune to commandblacklist where they have inventory trust
    default: op
  gpflags.bypass.commandblacklist.access:
    description: Makes a player immune to commandblacklist where they have access trust
    default: op
  gpflags.bypass.commandwhitelist.ownclaim:
    description: Makes a player immune to their own commandwhitelist flags
    default: op
  gpflags.bypass.entercommand:
    description: Makes a player immune to entercommand flags
    default: false
  gpflags.bypass.nochorusfruit.ownclaim:
    description: Makes a player immune to their own nochorusfruit flags
    default: op
  gpflags.bypass.noelytra:
    description: Makes a player immune to noelytra flags
    default: op
  gpflags.bypass.noelytra.ownclaim:
    description: Makes a player immune to their own noelytra flags
    default: op
  gpflags.bypass.noelytra.nonclaim:
    description: Makes a player immune to noelytra outside of claims
    default: op
  gpflags.bypass.noelytra.adminclaim:
    description: Makes a player immune to noelytra in adminclaims
    default: op
  gpflags.bypass.noelytra.manage:
    description: Makes a player immune to noelytra where they have manage trust
    default: op
  gpflags.bypass.noelytra.build:
    description: Makes a player immune to noelytra where they have build trust
    default: op
  gpflags.bypass.noelytra.inventory:
    description: Makes a player immune to noelytra where they have inventory trust
    default: op
  gpflags.bypass.noelytra.access:
    description: Makes a player immune to noelytra where they have access trust
    default: op
  gpflags.bypass.noenderpearl:
    description: Makes a player immune to noenderpearl flags
    default: op
  gpflags.bypass.noenderpearl.ownclaim:
    description: Makes a player immune to their own noenderpearl flags
    default: op
  gpflags.bypass.noenderpearl.nonclaim:
    description: Makes a player immune to noenderpearl outside of claims
    default: op
  gpflags.bypass.noenderpearl.adminclaim:
    description: Makes a player immune to noenderpearl in adminclaims
    default: op
  gpflags.bypass.noenderpearl.manage:
    description: Makes a player immune to noenderpearl where they have manage trust
    default: op
  gpflags.bypass.noenderpearl.build:
    description: Makes a player immune to noenderpearl where they have build trust
    default: op
  gpflags.bypass.noenderpearl.inventory:
    description: Makes a player immune to noenderpearl where they have inventory trust
    default: op
  gpflags.bypass.noenderpearl.access:
    description: Makes a player immune to noenderpearl where they have access trust
    default: op
  gpflags.bypass.noflight.ownclaim:
    description: Makes a player immune to their own noflight flags
    default: op
  gpflags.bypass.noflight.nonclaim:
    description: Makes a player immune to noflight outside of claims
    default: op
  gpflags.bypass.noflight.adminclaim:
    description: Makes a player immune to noflight in adminclaims
    default: op
  gpflags.bypass.noflight.manage:
    description: Makes a player immune to noflight where they have manage trust
    default: op
  gpflags.bypass.noflight.build:
    description: Makes a player immune to noflight where they have build trust
    default: op
  gpflags.bypass.noflight.inventory:
    description: Makes a player immune to noflight where they have inventory trust
    default: op
  gpflags.bypass.noflight.access:
    description: Makes a player immune to noflight where they have access trust
    default: op
  gpflags.bypass.noitemdrop:
    description: Makes a player immune to noitemdrop flags
    default: op
  gpflags.bypass.noitemdrop.ownclaim:
    description: Makes a player immune to their own noitemdrop flags
    default: op
  gpflags.bypass.noitemdrop.nonclaim:
    description: Makes a player immune to noitemdrop outside of claims
    default: op
  gpflags.bypass.noitemdrop.adminclaim:
    description: Makes a player immune to noitemdrop in adminclaims
    default: op
  gpflags.bypass.noitemdrop.manage:
    description: Makes a player immune to noitemdrop where they have manage trust
    default: op
  gpflags.bypass.noitemdrop.build:
    description: Makes a player immune to noitemdrop where they have build trust
    default: op
  gpflags.bypass.noitemdrop.inventory:
    description: Makes a player immune to noitemdrop where they have inventory trust
    default: op
  gpflags.bypass.noitemdrop.access:
    description: Makes a player immune to noitemdrop where they have access trust
    default: op
  gpflags.bypass.noitempickup.ownclaim:
    description: Makes a player immune to their own noitempickup flags
    default: op
  gpflags.bypass.noitempickup.nonclaim:
    description: Makes a player immune to noitempickup outside of claims
    default: op
  gpflags.bypass.noitempickup.adminclaim:
    description: Makes a player immune to noitempickup in adminclaims
    default: op
  gpflags.bypass.noitempickup.manage:
    description: Makes a player immune to noitempickup where they have manage trust
    default: op
  gpflags.bypass.noitempickup.build:
    description: Makes a player immune to noitempickup where they have build trust
    default: op
  gpflags.bypass.noitempickup.inventory:
    description: Makes a player immune to noitempickup where they have inventory trust
    default: op
  gpflags.bypass.noitempickup.access:
    description: Makes a player immune to noitempickup where they have access trust
    default: op
  gpflags.bypass.noitempickup:
    description: Makes a player immune to their own noitempickup flags
    default: op
  gpflags.bypass.nomcmmoskills:
    description: Makes a player immune to nomcmmoskills flags
    default: op
  gpflags.bypass.nomcmmoskills.ownclaim:
    description: Makes a player immune to their own nomcmmoskills flags
    default: op
  gpflags.bypass.nomcmmoskills.nonclaim:
    description: Makes a player immune to nomcmmoskills outside of claims
    default: op
  gpflags.bypass.nomcmmoskills.adminclaim:
    description: Makes a player immune to nomcmmoskills in adminclaims
    default: op
  gpflags.bypass.nomcmmoskills.manage:
    description: Makes a player immune to nomcmmoskills where they have manage trust
    default: op
  gpflags.bypass.nomcmmoskills.build:
    description: Makes a player immune to nomcmmoskills where they have build trust
    default: op
  gpflags.bypass.nomcmmoskills.inventory:
    description: Makes a player immune to nomcmmoskills where they have inventory trust
    default: op
  gpflags.bypass.nomcmmoskills.access:
    description: Makes a player immune to nomcmmoskills where they have access trust
    default: op
  gpflags.bypass.nomcmmoxp:
    description: Makes a player immune to nomcmmoxp flags
    default: op
  gpflags.bypass.nomcmmoxp.ownclaim:
    description: Makes a player immune to their own nomcmmoxp flags
    default: op
  gpflags.bypass.nomcmmoxp.nonclaim:
    description: Makes a player immune to nomcmmoxp outside of claims
    default: op
  gpflags.bypass.nomcmmoxp.adminclaim:
    description: Makes a player immune to nomcmmoxp in adminclaims
    default: op
  gpflags.bypass.nomcmmoxp.manage:
    description: Makes a player immune to nomcmmoxp where they have manage trust
    default: op
  gpflags.bypass.nomcmmoxp.build:
    description: Makes a player immune to nomcmmoxp where they have build trust
    default: op
  gpflags.bypass.nomcmmoxp.inventory:
    description: Makes a player immune to nomcmmoxp where they have inventory trust
    default: op
  gpflags.bypass.nomcmmoxp.access:
    description: Makes a player immune to nomcmmoxp where they have access trust
    default: op
  gpflags.command.setclaimflag:
    description: Grants permission to use /SetClaimFlag.
    default: op
  gpflags.command.unsetclaimflag:
    description: Grants permission to use /UnSetClaimFlag.
    default: op
  gpflags.command.setworldflag:
    description: Grants permission to use /SetWorldFlag.
    default: op
  gpflags.command.unsetworldflag:
    description: Grants permission to use /UnSetWorldFlag.
    default: op
  gpflags.command.setserverflag:
    description: Grants permission to use /SetServerFlag.
    default: op
  gpflags.command.unsetserverflag:
    description: Grants permission to use /UnSetServerFlag.
    default: op
  gpflags.command.defaultflags:
    description: Grants permission to use /SetDefaultClaimFlag and /UnSetDefaultClaimFlag.
    default: op
  gpflags.command.listflags:
    description: Grants permission to use /ListClaimFlags.
    default: op
  gpflags.command.reload:
    description: Grants permission to use /GPFlags reload.
    default: op
    children:
      gpflags.command.gpflags: true
  gpflags.command.help:
    description: Grants permission to use /GPFlags help.
    default: true
    children:
      gpflags.command.gpflags: true
  gpflags.flag.allflags:
    description: Grants permission to apply/remove all flags. (depreciated)
    default: op
    children:
      gpflags.flag.*: true